# Generated by Django 5.2.5 on 2025-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Done'), ('postponed', 'Postponed')], default='in_progress', max_length=50)),
            ],
        ),
    ]
